# Generated by Django 4.2 on 2023-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('relative_name', models.CharField(max_length=200)),
                ('relative_address', models.CharField(max_length=200)),
                ('reason_for_admission', models.TextField()),
            ],
        ),
    ]
